### ISSUE TITLE
installation problem - incomplete requirements.txt

### ISSUE THREAD

**Issue by chymian** [e-p-armstrong/augmentoolkit#10]
hi, I installed in a new conda env and when I run the 2nd cell of the notebook, I get 

```log
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
```
one __MUST__ install aphrodite to get it to run…

and do you have a __discord-server__?

and PS: groq runs into rate limiting… how to make it work?

**Comment by e-p-armstrong** [comment]
1) you shouldn't need to have aphrodite to get it to run, I'm running things on my macbook all the time (which literally can't install aphrodite) and it works fine. I think that message is not an error, but it's popping up because you're using the transformers package for the tokenizer used in the chunking logic (you only need the tokenizer not the models). So it's a warning for people using transformers for typical usecases, but it's actually not a concern here.

2) I don't have a discord server, it might be good to make one though so I'll think on that! In the meantime if you want to talk augmentoolkit there's a corner for it over in FoxEngineAI's discord server: https://discord.gg/foxengine-ai

3) If rate limits are a problem, adjust the concurrency limit in config.yaml
