### ISSUE TITLE
Dataset generation for TGI 1.2.0

### ISSUE THREAD

**Issue by pallavijaini0525** [e-p-armstrong/augmentoolkit#7]
Thank you for this amazing tool.

I intend to utilize this tool to transform my PDF data into a fine-tuning dataset for LLAMA-7B. Presently, when utilizing TGI version 1.2.0 for the inference API, the processing.py fails saying  /chat/completions endpoint is missing. TGI 1.2.0 does not support open AI message API. Is there a way to adapt the code to function with alternative inference APIs such as torchserve or with TGI 2.0?

**Comment by e-p-armstrong** [comment]
Yeah sure, you can do that. you'll want to look into the submit_chat and submit_completion methods in the EngineWrapper class in engine_wrapper_class.py, and also change the __init__ method of that class to, if mode=="torchserve" or something, set the object's client object to an API object for the specific API you want instead of AsyncOpenAI
![image](https://github.com/e-p-armstrong/augmentoolkit/assets/64122766/5345de94-842d-4d13-9e48-d7d9c223b9bd)
When you're done with the init method that's when you'll go into the submit_ methods on EngineWrapper and modify them to work with whatever API library you're using by adding an if statement with if self.mode=="torchserve" and then the logic you need.

Then you go into config.yaml and set MODE to torchserve and you SHOULD be good to go unless I missed something. Let me know if it works! And actually if you manage to do it without breaking other functionality I'd welcome the changes as a PR to support Torchserve

**Comment by e-p-armstrong** [comment]
Closing because I think this problem has been resolved
